# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.t411:
        class: AppBundle\Service\T411Service
        arguments:
            - "%t411_domain%"
            - "%t411_login%"
            - "%t411_pass%"
