# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.t411:
        class: AppBundle\Service\T411Service
        arguments:
            - "%t411_domain%"
            - "%t411_login%"
            - "%t411_pass%"
            - "%t411_path_torrent%"

    app.nas:
        class: AppBundle\Service\NasService
        arguments:
            - "%path_tvshow%"
            - "%chown_path%"

    app.synology:
        class: AppBundle\Service\SynologyService
        arguments:
            - "%nas_ip%"
            - "%nas_port%"
            - "%nas_protocol%"
            - "%nas_version%"
            - "%nas_login%"
            - "%nas_pass%"